# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: micampe/marytharin.com

media_folder: /public/media
public_folder: /media

collections:
  - name: pages
    label: Pages
    folder: content
    create: true
    delete: true
    format: toml-frontmatter
    extension: md
    slug: "{{slug}}"
    fields:
      - { name: title,  label: Title,           widget: string }
      - { name: weight, label: Order in menu,   widget: number, value_type: int, default: 10 }
      - { name: body,   label: Body,            widget: markdown }
    index_file:
      label: Home Page
      icon: home
      format: toml-frontmatter
      fields:
        - { name: title,   label: Title, widget: string }
        - { name: body,    label: Body,  widget: markdown }
